#!/bin/bash

for i in `awk ' { print $1 } ' quota_exceed_userlist` 
do
mail -b desh -s "Please delete some data from your Internet terminal (nomachine)" $i << EOF
Hi `dnwho $i -e | grep name | cut -d ":" -f2 | sed -e 's/^[ \t]*//'`,

Please delete some data from your Internet terminal (nomachine) so as to avoid further login error as your disk usage on it is almost full.

For more information on how to lower your quota please read these notes:
http://dnet.dneg.com/display/TECH/Home+Quota

Regards,
Deepak
EOF
done
