#!/bin/bash

for i in `awk ' { print $1 } ' quota_exceed_userlist` 
do
mail -b kbm -s "Please delete some data from your login" $i << EOF
Hi `dnwho $i -e | grep name | cut -d ":" -f2 | sed -e 's/^[ \t]*//'`,

Please delete some data from your login so as to avoid further login error as your disk usage is almost full.

Following is the breakdown of your usage

`sudo du -sh /u/$i/* | sort -hr | grep -v ^0` 

